version: "3.9"
services:
  nginx-app:
    image: mnikhoa/nginx:latest
    container_name: nginx_app_container
    ports:
      - "80:80"
  # my-app:
  #   image: ${docker-registry}/my-app:1.0
  #   ports:
  #     - 3000:3000
  mongodb:
    image: mongo
    container_name: mongo_container
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    container_name: mongo_express_container
    restart: always # fixes MongoNetworkError when mongodb is not ready when mongo-express starts
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
#   #mnikhoa/my-app:
#   #  image: mnikhoa/my-app:1.0
#   #  ports:
#   #    - 3000:3000
volumes:
  mongo-data:
    driver: local
